### ISSUE TITLE
How to setup : URL_STORAGE_REFERENCE = "XXXXXXXXXXX" ?

### ISSUE THREAD

**Issue by samllchiang** [AleBarreto/FirebaseAndroidChat#6]
Hi,
where i can find the  URL_STORAGE_REFERENCE to fill the correct value.
thanks

**Comment by AleBarreto** [comment]
![URL STORAGE](https://camo.githubusercontent.com/56b5b829f85f8cbcd8e5b8db0f1586fe5a8973be/687474703a2f2f642e70722f692f316c4b6a512e706e67)

**Comment by samllchiang** [comment]
Click menu item "Send Location" does not work show below photo:
![image](https://cloud.githubusercontent.com/assets/6982698/18192022/d743230c-7102-11e6-9488-fa51d82c3fd3.png)
 Please help me to enable App.
thanks
